In [183]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
import numpy
from kneed import KneeLocator

In [208]:
df = pd.read_csv('internetSpeed_Indonesia - 2020.csv')
df = df.dropna()
df.head(10)

Year           Location  Download  Upload           UMR  \
0  2020               Aceh      10.2     4.8  2 916 810,00   
1  2020               Bali      11.6     6.9  2 297 969,00   
2  2020    Bangka Belitung      10.6     4.5  2 976 706,00   
3  2020             Banten      10.4     4.9  2 267 990,00   
4  2020           Bengkulu       9.5     4.4  2 040 407,00   
5  2020        Jawa Tengah       9.6     5.1  1 605 396,00   
6  2020  Kalimantan Tengah      11.0     7.1  2 663 435,00   
7  2020    Sulawesi Tengah      13.6     4.8  2 123 040,00   
8  2020         Jawa Timur      11.3     5.5  1 630 059,00   
9  2020   Kalimantan Timur      13.2     7.0  2 747 561,00   

   persentase pengguna internet Jumlah penduduk  
0                         71.97       5.388.100  
1                         85.67       4.414.400  
2                         78.35       1.469.800  
3                         84.07      12.895.300  
4                         71.69       1.994.300  
5                         79.66      34.738.200  
6                         76.57       2.686.300  
7                         68.70       3.081.700  
8                         77.21      39.955.900  
9                         86.87       3.664.700

In [185]:
df2 = pd.read_csv('internetSpeed_Indonesia - 2021.csv')
df2 = df2.dropna()
df2.head(10)

Year           Location  Download  Upload           UMR  \
0  2021               Aceh     20.59    5.31  3.160.000,00   
1  2021               Bali     24.71   16.98  2.494.000,00   
2  2021    Bangka Belitung     19.17    7.02  3.230.023,00   
3  2021             Banten     21.30    8.08  4.230.792,65   
4  2021           Bengkulu     17.74    4.77  2.215.000,00   
5  2021        Jawa Tengah     17.55    6.45  1.813.011,00   
6  2021  Kalimantan Tengah     20.31    6.64  2.903.144.00   
7  2021    Sulawesi Tengah     16.76    4.64  2.303.711,00   
8  2021         Jawa Timur     17.05    6.53  4.300.479,00   
9  2021   Kalimantan Timur     20.14    6.43  2.981.378,00   

   persentase pengguna internet Jumlah penduduk  
0                         75.54       5.334.000  
1                         87.80       4.363.000  
2                         82.89       1.473.000  
3                         87.45      12.061.000  
4                         78.03       2.033.000  
5                         82.88      36.743.000  
6                         80.27       2.702.000  
7                         76.51       3.022.000  
8                         79.66      40.879.000  
9                         89.67       3.808.000

In [186]:
df3 = pd.read_csv('internetSpeed_Indonesia - 2022.csv')
df3 = df3.dropna()
df3.head(10)

Year           Location  Download  Upload           UMR  \
0  2022               Aceh     22.56    9.42  3.116.460,00   
1  2022               Bali     29.46   24.54  2.516.971,00   
2  2022    Bangka Belitung     21.76   13.58  3.264.884,00   
3  2022             Banten     26.34   11.65  2.501.203,11   
4  2022           Bengkulu     19.25    9.08  2.238.094,31   
5  2022        Jawa Tengah     17.98    9.50  1.812.935,00   
6  2022  Kalimantan Tengah     22.64   10.15  2.922.516,09   
7  2022    Sulawesi Tengah     19.32    9.58  2.390.739,00   
8  2022         Jawa Timur     18.83    8.77  1.891.567,12   
9  2022   Kalimantan Timur     22.18   10.23  3.014.497,22   

   persentase pengguna internet Jumlah penduduk  Unnamed: 7  
0                         80.83       5.380.000       75.54  
1                         93.95       4.290.000       87.80  
2                         88.69       1.470.000       82.89  
3                         93.57      12.150.000       87.45  
4                         83.49       2.050.000       78.03  
5                         88.68      37.490.000       82.88  
6                         85.89       2.670.000       80.27  
7                         81.87       3.070.000       76.51  
8                         85.24      41.140.000       79.66  
9                         95.95       3.890.000       89.67

In [187]:
x = df.iloc[:,[3,4]]
x = x.values.tolist()
x = numpy.array(x)
print(x[0])

['4.8' '2 916 810,00']


In [188]:
x2 = df2.iloc[:,[3,4]]
x2 = x2.values.tolist()
x2 = numpy.array(x2)
print(x2[0])

['5.31' '3.160.000,00']


In [189]:
x3 = df3.iloc[:,[3,4]]
x3 = x3.values.tolist()
x3 = numpy.array(x3)
print(x3[0])

['9.42' '3.116.460,00']


In [206]:
dfc = df.iloc[:,[2,3,4]]
dfc = dfc.values.tolist()

dfc2 = df2.iloc[:,[2,3,4]]
dfc2 = dfc2.values.tolist()

dfc3 = df3.iloc[:,[2,3,4]]
dfc3 = dfc3.values.tolist()

# print(float(dfc[0][1]) + float(dfc[0][0]))
for i in range (33):
    x[i][0] = round(((float(dfc[i][1]) + float(dfc[i][0])))/2,2)
    x2[i][0] = round(((float(dfc2[i][1]) + float(dfc2[i][0])))/2,2)
    x3[i][0] = round(((float(dfc3[i][1]) + float(dfc3[i][0])))/2,2)

    x[i][1] = dfc[i][2][:-3].replace(" ", "")
    x2[i][1] = dfc2[i][2][:-3].replace(" ", "")
    x3[i][1] = dfc3[i][2][:-3].replace(" ", "")
    
    # x[i][1] = int(dfc[i][2])
    # x2[i][1] = int(dfc2[i][2])
    # x3[i][1] = int(dfc3[i][2])

print(x)

[['7.5' '2916810']
 ['9.25' '2297969']
 ['7.55' '2976706']
 ['7.65' '2267990']
 ['6.95' '2040407']
 ['7.35' '1605396']
 ['9.05' '2663435']
 ['9.2' '2123040']
 ['8.4' '1630059']
 ['10.1' '2747561']
 ['10.5' '1795000']
 ['7.95' '2384020']
 ['7.5' '3940973']
 ['7.55' '2423889']
 ['7.75' '2241270']
 ['11.45' '2400664']
 ['10.4' '2765463']
 ['7.75' '2508091']
 ['8.25' '3051076']
 ['11.45' '3240900']
 ['9.45' '2662026']
 ['7.55' '2769754']
 ['9.1' '2351870']
 ['8.4' '2651782']
 ['7.75' '2860382']
 ['8.05' '1570923']
 ['7.75' '1668373']
 ['8.3' '2211500']
 ['9.55' '2012610']
 ['12.75' '2934500']
 ['8.35' '2381000']
 ['6.95' '2289220']
 ['8.35' '2\u2009860\u2009382']
 ['5.9' '2 303 403,00']]


In [191]:
print(x2)

[['12.95' '3.160.000,00']
 ['20.84' '2.494.000,00']
 ['13.1' '3.230.023,00']
 ['14.69' '4.230.792,65']
 ['11.25' '2.215.000,00']
 ['12.0' '1.813.011,00']
 ['13.47' '2.903.144.00']
 ['10.7' '2.303.711,00']
 ['11.79' '4.300.479,00']
 ['13.29' '2.981.378,00']
 ['12.62' '1.950.000,00']
 ['11.54' '2.586.900,00']
 ['18.75' '4.416.186,00']
 ['12.23' '2.630.162,00']
 ['11.52' '2.400.000,00']
 ['11.54' '2.604.961,00']
 ['13.08' '3.000.803,00']
 ['12.34' '2.721.530,00']
 ['12.51' '3.310.721,00']
 ['12.88' '3.516.700,00']
 ['11.81' '2.888.563,00']
 ['13.79' '3.005.383,00']
 ['11.77' '2.552.014,00']
 ['13.63' '2.903.144,00']
 ['13.96' '3.043.111,00']
 ['12.7' '1.765.608,00']
 ['14.3' '1.810.351,00']
 ['13.04' '2.399.698,00']
 ['11.98' '2.183.883,00']
 ['11.98' '3.134.600,00']
 ['11.56' '2.571.328,00']
 ['13.54' '2.484.041,00']
 ['12.94' '3.165.876,00']
 ['7.36' '2.499.422,00']]


In [192]:
print(x3)

[['15.99' '3.116.460,00']
 ['27.0' '2.516.971,00']
 ['17.67' '3.264.884,00']
 ['19.0' '2.501.203,11']
 ['14.16' '2.238.094,31']
 ['13.74' '1.812.935,00']
 ['16.39' '2.922.516,09']
 ['14.45' '2.390.739,00']
 ['13.8' '1.891.567,12']
 ['16.2' '3.014.497,22']
 ['16.04' '1.975.000,00']
 ['14.05' '2.800.580,00']
 ['23.2' '4.641.854,00']
 ['14.79' '2.698.940,87']
 ['13.55' '2.440.486,18']
 ['14.78' '2.619.312,83']
 ['15.61' '3.016.738,00']
 ['18.04' '2.862.231,00']
 ['12.34' '3.310.723,00']
 ['15.98' '3.561.932,00']
 ['14.77' '2.938.564,01']
 ['15.16' '3.050.172,00']
 ['13.8' '2.576.016,96']
 ['17.06' '2.906.473,32']
 ['17.48' '3.144.446,00']
 ['14.63' '1.840.915,53']
 ['18.23' '1.841.487,00']
 ['16.46' '2.434.328,00']
 ['13.58' '2.207.212,00']
 ['14.91' '3.200.000,00']
 ['13.26' '2.678.863,10']
 ['15.36' '2.512.539,00']
 ['15.89' '3.165.876,00']
 ['9.66' '2.522.609,94']]


In [193]:
distortions = []
for i in range(1, 11):
    km = KMeans(
        n_clusters=i, init='random',
        n_init=10, max_iter=300,
        tol=1e-04, random_state=0
    )
    km.fit(x) 
    distortions.append(km.inertia_)

kl = KneeLocator(range(1, 11), distortions, curve="convex", direction="decreasing")
kl.elbow

ValueError: could not convert string to float: '2 916 810,00'

In [ ]:
km = KMeans (n_clusters= kl.elbow,
init = 'random', n_init= 10, 
max_iter= 300, tol= 0.01, random_state=0 
)

NameError: name 'kl' is not defined

In [ ]:
y_km = km.fit_predict(x)
print(y_km)

[1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 2 0 1 1 2 0 1 0 1 1 1 1 1 0 2 1 1 1 0]


In [ ]:
y_km2 = km.fit_predict(x2)
print(y_km2)

[0 2 0 0 1 1 0 1 1 0 0 1 2 1 1 1 0 0 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 0]


In [ ]:
y_km3 = km.fit_predict(x3)
print(y_km3)

[2 1 2 2 0 0 2 0 0 2 2 0 1 0 0 0 2 2 0 2 0 0 0 2 2 0 2 2 0 0 0 2 2 0]
